POST http://localhost:8080/login
Content-Type: application/json

{"username":"viktorija.mileva","password":"vm"}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
  var jwt=response.body
  client.global.set("jwt", response.body)
});
%}
